---
- name: Apply CIS Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
  hosts: all
  become: true
  become_method: sudo
  tasks: 
    - name: set password for ec2-user
      ansible.builtin.user:
        name: ec2-user
        password: "{{ ec2_password|password_hash('sha512') }}"
    - name: Update clout-init generated sudoers
      ansible.builtin.blockinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ec2-user ALL=(ALL)	ALL

    - name: Copy rsyslog config
      ansible.builtin.copy:
        src: "31-aap.conf"
        dest: "/etc/rsyslog.d/31-aap.conf"
        mode: "0644"
    - name: Restart service rsyslog
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: rsyslog
